# Generated by Django 4.0.5 on 2022-06-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_whyus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimages',
            options={'verbose_name': 'Slider Image', 'verbose_name_plural': 'Slider Images'},
        ),
        migrations.AlterModelOptions(
            name='websiteinfo',
            options={'verbose_name': 'Website Information', 'verbose_name_plural': 'Website Informations'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name': 'Why Us', 'verbose_name_plural': 'Why Us'},
        ),
    ]
